// Centralized mock data and site defaults.
export const MOCK_TEAMS = [
  {
    id: 't1',
    name: 'RoboTitans India',
    country: 'India',
    flag: '🇮🇳',
    rank: 1,
    points: 2450,
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=RoboTitans',
    wins: 42,
    losses: 5,
    earnings: '$120,000',
    worldTitles: 2,
    history: 'Founded in 2018, RoboTitans have dominated the Asian circuit.',
    participations: [
      { year: 2022, placement: 'Champions' },
      { year: 2023, placement: 'Runner-up' },
      { year: 2024, placement: 'Semi-final' },
    ],
    players: [
      {
        id: 1,
        name: 'Aarav Patel',
        role: 'Captain / Pilot',
        matches: 45,
        winRate: '88%',
        earnings: '$55k',
        image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
      },
      {
        id: 2,
        name: 'Priya Sharma',
        role: 'Lead Programmer',
        matches: 42,
        winRate: '85%',
        earnings: '$40k',
        image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop',
      },
      {
        id: 3,
        name: 'Kabir Mehta',
        role: 'Systems Architect',
        matches: 30,
        winRate: '81%',
        earnings: '$25k',
        image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
      },
    ],
  },
  {
    id: 't2',
    name: 'Cyber United UK',
    country: 'UK',
    flag: '🇬🇧',
    rank: 2,
    points: 2380,
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=CyberUK',
    wins: 38,
    losses: 8,
    earnings: '$95,000',
    worldTitles: 1,
    history: 'European Champions 2024.',
    participations: [
      { year: 2022, placement: 'Quarter-final' },
      { year: 2023, placement: 'Champions' },
      { year: 2024, placement: 'Group Stage' },
    ],
    players: [
      {
        id: 4,
        name: 'Sarah Jenkins',
        role: 'Captain',
        matches: 30,
        winRate: '70%',
        earnings: '$35k',
        image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
      },
      {
        id: 5,
        name: 'Liam Carter',
        role: 'Mechanical Lead',
        matches: 28,
        winRate: '68%',
        earnings: '$22k',
        image: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=400&h=400&fit=crop',
      },
    ],
  },
  {
    id: 't3',
    name: 'Desert Falcons UAE',
    country: 'UAE',
    flag: '🇦🇪',
    rank: 7,
    points: 1890,
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=DesertFalcons',
    wins: 25,
    losses: 11,
    earnings: '$62,000',
    worldTitles: 0,
    history: 'Fan favorites known for precision drone maneuvers.',
    participations: [
      { year: 2023, placement: 'Top 16' },
      { year: 2024, placement: 'Top 8' },
    ],
    players: [
      {
        id: 6,
        name: 'Amira Al Mansoori',
        role: 'Lead Pilot',
        matches: 26,
        winRate: '74%',
        earnings: '$18k',
        image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400&fit=crop',
      },
    ],
  },
];

export const THINK_TANK_LOGOS = [
  'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/2560px-Amazon_logo.svg.png',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/2560px-Google_2015_logo.svg.png',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/2048px-Microsoft_logo.svg.png',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/IBM_logo.svg/2560px-IBM_logo.svg.png',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Nvidia_logo.svg/2560px-Nvidia_logo.svg.png',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Cisco_logo_blue_2016.svg/2560px-Cisco_logo_blue_2016.svg.png',
];

export const CAREERS = [
  { id: 1, title: 'Global Events Manager', location: 'Dubai / Hybrid', type: 'Full-time' },
  { id: 2, title: 'Technical Rulebook Author', location: 'Remote', type: 'Contract' },
  { id: 3, title: 'Regional Partner Coordinator', location: 'Singapore', type: 'Full-time' },
];

export const GAME_CATEGORIES = [
  {
    id: 'roborace',
    name: 'Robo Race',
    desc: 'High speed autonomous racing on variable terrain.',
    players: '12k+',
    prize: '$50,000',
    icon: '🏎️',
    rulebook: 'https://example.com/rules/roborace.pdf',
    model: 'Arena 3D: Canyon Sprint',
    scoring: 'Lap time + obstacle penalties',
  },
  {
    id: 'robosoccer',
    name: 'Robo Soccer',
    desc: 'Tactical team sport. 3v3 autonomous bots.',
    players: '8k+',
    prize: '$35,000',
    icon: '⚽',
    rulebook: 'https://example.com/rules/robosoccer.pdf',
    model: 'Arena 3D: Hex Turf',
    scoring: 'Goals + possession dominance',
  },
  {
    id: 'droneracing',
    name: 'Drone Racing',
    desc: 'FPV obstacle course racing at 100mph.',
    players: '15k+',
    prize: '$60,000',
    icon: '🚁',
    rulebook: 'https://example.com/rules/droneracing.pdf',
    model: 'Arena 3D: Neon Gates',
    scoring: 'Fastest lap; crash penalties',
  },
  {
    id: 'sumobot',
    name: 'Sumo Bot',
    desc: 'Strength and strategy combat in the ring.',
    players: '25k+',
    prize: '$25,000',
    icon: '🥋',
    rulebook: 'https://example.com/rules/sumobot.pdf',
    model: 'Arena 3D: Dual Circle',
    scoring: 'Ring outs + control points',
  },
  {
    id: 'water',
    name: 'Water Rocket',
    desc: 'Precision and distance challenges.',
    players: '10k+',
    prize: '$15,000',
    icon: '🚀',
    rulebook: 'https://example.com/rules/water-rocket.pdf',
    model: 'Arena 3D: Splashway',
    scoring: 'Distance + accuracy',
  },
  {
    id: 'innov',
    name: 'Innovation Challenge',
    desc: 'Solving real world problems with tech.',
    players: '5k+',
    prize: '$75,000',
    icon: '💡',
    rulebook: 'https://example.com/rules/innovation.pdf',
    model: 'Arena 3D: Prototype Lab',
    scoring: 'Impact + feasibility',
  },
  {
    id: 'battlebots',
    name: 'Battle Bots',
    desc: 'Combat arena for tactical destruction.',
    players: '18k+',
    prize: '$45,000',
    icon: '🛡️',
    rulebook: 'https://example.com/rules/battlebots.pdf',
    model: 'Arena 3D: Steel Yard',
    scoring: 'Damage + control',
  },
  {
    id: 'agrodrone',
    name: 'Agro Drone',
    desc: 'Precision spraying and seeding challenges.',
    players: '6k+',
    prize: '$28,000',
    icon: '🌾',
    rulebook: 'https://example.com/rules/agrodrone.pdf',
    model: 'Arena 3D: Farmlands',
    scoring: 'Coverage + conservation',
  },
  {
    id: 'rescue',
    name: 'Rescue Relay',
    desc: 'Autonomous bots for disaster response.',
    players: '7k+',
    prize: '$32,000',
    icon: '🚒',
    rulebook: 'https://example.com/rules/rescue.pdf',
    model: 'Arena 3D: Quake Zone',
    scoring: 'Victim retrieval + time',
  },
];

export const NEWS_ITEMS = [
  {
    id: 1,
    category: 'Regulation',
    tag: 'REGULATION',
    date: 'Nov 27, 2025',
    title: 'New Autonomous Drone Regulations (ADR-25) Released',
    desc: 'The board has officially ratified the new guidelines for autonomous flight.',
    body: 'The World Robotics Society has officially ratified the new Autonomous Drone Regulations (ADR-25), establishing comprehensive safety protocols and operational standards for drone racing competitions worldwide. These regulations will be synchronized across all partner subdomains via middleware, ensuring consistent enforcement from local qualifiers to the World Cup finals.',
    featuredImage: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&h=500&fit=crop',
    sampleImages: [
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&fit=crop',
    ],
    fullContent: [
      'The World Robotics Society has officially ratified the new Autonomous Drone Regulations (ADR-25), establishing comprehensive safety protocols and operational standards for drone racing competitions worldwide. These regulations will be synchronized across all partner subdomains via middleware, ensuring consistent enforcement from local qualifiers to the World Cup finals.',
      'The ADR-25 framework introduces mandatory telemetry logging, real-time altitude restrictions, and automated collision avoidance systems. All participating teams must submit their drone specifications for pre-competition certification, with compliance checks performed by AI Referee systems at every event.',
      'Partner nations will receive automatic rulebook updates through the federated middleware, eliminating version conflicts and ensuring all regional qualifiers operate under identical standards. This marks a significant milestone in WORSO\'s mission to create a unified, safe, and fair competitive environment for autonomous sports.',
    ],
  },
  {
    id: 2,
    category: 'Event',
    tag: 'EVENT',
    date: 'Nov 26, 2025',
    title: 'Technoxian World Cup Venue Finalized: Dubai Exhibition Centre',
    desc: 'The largest robotics arena in history will be constructed at DEC.',
    body: 'WORSO has announced that the Technoxian World Cup 2026 will be held at the Dubai Exhibition Centre, marking the largest robotics competition venue in history. The facility will feature nine dedicated competition zones, innovation expo halls, and spectator concourses capable of hosting over 2.5 million visitors across the four-day championship.',
    featuredImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&h=500&fit=crop',
    sampleImages: [
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
    ],
    fullContent: [
      'WORSO has announced that the Technoxian World Cup 2026 will be held at the Dubai Exhibition Centre, marking the largest robotics competition venue in history. The facility will feature nine dedicated competition zones, innovation expo halls, and spectator concourses capable of hosting over 2.5 million visitors across the four-day championship.',
      'The Dubai Exhibition Centre will undergo a $50 million transformation to accommodate the World Cup, including custom-built arenas for each competition category, state-of-the-art broadcasting facilities, and integrated AI Referee monitoring systems. The venue will serve as a model for future partner-hosted events.',
      'Registration for teams, visitors, and exhibitors opened simultaneously across all partner subdomains, with unified payment processing and real-time availability tracking. The federated architecture ensures that capacity limits and ticket sales are synchronized globally, preventing overselling and ensuring fair access.',
    ],
  },
  {
    id: 3,
    category: 'Partnership',
    tag: 'PARTNERSHIP',
    date: 'Nov 25, 2025',
    title: 'Worso Welcomes South Korea as Strategic Partner',
    desc: 'The KRA officially joins the federation.',
    body: 'The Korean Robotics Association (KRA) has officially joined WORSO as a strategic partner, receiving approval for the korea.worso.org subdomain. The partnership will enable local qualifiers, Korean-language content, and regional sponsors while maintaining global rulebook compliance through federated middleware architecture.',
    featuredImage: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop',
    sampleImages: [
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop',
    ],
    fullContent: [
      'The Korean Robotics Association (KRA) has officially joined WORSO as a strategic partner, receiving approval for the korea.worso.org subdomain. The partnership will enable local qualifiers, Korean-language content, and regional sponsors while maintaining global rulebook compliance through federated middleware architecture.',
      'KRA will host regional qualifiers for the Technoxian World Cup, with top teams advancing to the global finals. The Korean micro-site will feature localized content, regional event calendars, and Korean-language rulebook translations, all while maintaining the core WORSO brand identity.',
      'This partnership brings WORSO\'s total partner network to 96 nations, with South Korea representing a key market in the Asia-Pacific region. The federated model allows KRA to operate autonomously while contributing to the global rankings and data layer.',
    ],
  },
  {
    id: 4,
    category: 'Technology',
    tag: 'TECH',
    date: 'Nov 24, 2025',
    title: 'AI Referee System Launches Across All Partner Portals',
    desc: 'Real-time officiating powered by machine learning now available globally.',
    body: 'WORSO has deployed its AI Referee system across all partner subdomains, enabling real-time rule enforcement, scoring validation, and dispute resolution. The system uses federated learning to improve accuracy while maintaining data privacy across regional boundaries.',
    featuredImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=500&fit=crop',
    sampleImages: [
      'https://images.unsplash.com/photo-1555255707-c07966088b7b?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop',
    ],
    fullContent: [
      'WORSO has deployed its AI Referee system across all partner subdomains, enabling real-time rule enforcement, scoring validation, and dispute resolution. The system uses federated learning to improve accuracy while maintaining data privacy across regional boundaries.',
      'The AI Referee analyzes telemetry data, video feeds, and sensor inputs to make instant decisions on rule violations, scoring disputes, and safety interventions. Human referees can override AI decisions, but the system\'s accuracy rate of 98.7% has significantly reduced appeals and improved event flow.',
      'Federated learning allows the AI to improve from events across all partner nations without sharing sensitive competition data. Each partner\'s local events contribute to the global model while maintaining complete data sovereignty.',
    ],
  },
  {
    id: 5,
    category: 'Markets',
    tag: 'MARKETS',
    date: 'Nov 23, 2025',
    title: 'Prize Pool Reaches Record $250,000 for World Cup 2026',
    desc: 'Corporate sponsorships drive unprecedented prize distribution.',
    body: 'The Technoxian World Cup 2026 prize pool has reached a record-breaking $250,000, driven by strategic partnerships with leading technology corporations. Prize distribution will be transparent and auditable, with real-time tracking available on all partner micro-sites through unified payment gateway integration.',
    featuredImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=500&fit=crop',
    sampleImages: [
      'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1511578314322-379afb476865?w=400&h=300&fit=crop',
    ],
    fullContent: [
      'The Technoxian World Cup 2026 prize pool has reached a record-breaking $250,000, driven by strategic partnerships with leading technology corporations. Prize distribution will be transparent and auditable, with real-time tracking available on all partner micro-sites through unified payment gateway integration.',
      'Prize money will be distributed across all nine competition categories, with the Innovation Challenge category receiving the largest share at $75,000. Teams can track their earnings in real-time through the unified dashboard, with automatic tax documentation generated for international participants.',
      'Corporate sponsors including major tech firms have committed to multi-year partnerships, ensuring prize pool growth and long-term financial stability for the sport. The federated architecture allows sponsors to target specific regions while contributing to the global prize pool.',
    ],
  },
];

export const DEFAULT_SITES = {
  global: {
    id: 'global',
    name: 'WORSO Global',
    logo_text: 'WORSO',
    sub_text: 'WORLD ROBOTICS SOCIETY',
    theme: 'blue',
    colors: {
      primary: 'bg-blue-600',
      hover: 'hover:bg-blue-700',
      text: 'text-blue-600',
      gradient: 'bg-[#0f172a]',
    },
    is_partner: false,
    local_events: [],
  },
  uae: {
    id: 'uae',
    name: 'TECHNOXIAN UAE',
    logo_text: 'TECHNOXIAN UAE',
    sub_text: 'OFFICIAL REGIONAL CHAPTER',
    theme: 'emerald',
    colors: {
      primary: 'bg-emerald-600',
      hover: 'hover:bg-emerald-700',
      text: 'text-emerald-500',
      gradient: 'bg-[#022c22]',
    },
    is_partner: true,
    local_events: [
      { id: 1, title: 'Dubai Schools Challenge', date: 'Jan 15, 2026', location: 'GEMS Academy', status: 'Open' },
      { id: 2, title: 'Abu Dhabi Zonal Qualifier', date: 'Feb 20, 2026', location: 'ADNEC', status: 'Upcoming' },
    ],
  },
};

